// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAxfYoj55zfh5FJqQ1yu7JcsKToKuT1y2o',
    appId: '1:518822984643:android:481317bfdd370db4769b76',
    messagingSenderId: '518822984643',
    projectId: 'myshittytaskapp',
    databaseURL: 'https://myshittytaskapp-default-rtdb.firebaseio.com',
    storageBucket: 'myshittytaskapp.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBesX2B7_cn3YSGeM99-YOPsY1gEWnG5rA',
    appId: '1:518822984643:ios:83c829504017a2f0769b76',
    messagingSenderId: '518822984643',
    projectId: 'myshittytaskapp',
    databaseURL: 'https://myshittytaskapp-default-rtdb.firebaseio.com',
    storageBucket: 'myshittytaskapp.appspot.com',
    iosClientId: '518822984643-mse4uf9f2c08dd2a55ksl8v1slhgl12d.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterhw4',
  );
}
